import fs from 'fs';
import path from 'path';
import * as cheerio from 'cheerio';
import { 
  buildAssetRenameMap, 
  copyAssetsOrganized, 
  rewriteHtmlPaths, 
  mergeCss, 
  extractPageCss,
  formatWithPrettier,
  rewriteInternalLinks,
  STATIC_INTERACTIVITY_SCRIPT,
  UNIVERSAL_STUBS_SCRIPT,
  generateRouteNavigatorScript,
  generateRoutes,
  generateFetchRewriteScript
} from './exportUtils.js';

export async function generate(sourceDir, outputDir, cloneRecord, pages, assets) {
  // 1. Build rename map and copy assets
  const renameMap = buildAssetRenameMap(assets);
  const pathMapping = copyAssetsOrganized(sourceDir, outputDir, assets, renameMap);
  const routes = generateRoutes(pages);
  
  // 2. Merge CSS
  const mergedCss = mergeCss(sourceDir, assets, pages, pathMapping);
  const cssDir = path.join(outputDir, 'css');
  fs.mkdirSync(cssDir, { recursive: true });
  const formattedCss = await formatWithPrettier(mergedCss, 'css');
  fs.writeFileSync(path.join(cssDir, 'styles.css'), formattedCss);

  // 3. Process each HTML page
  for (const page of pages) {
    const srcPath = path.join(sourceDir, page.local_path);
    if (!fs.existsSync(srcPath)) continue;

    let html = fs.readFileSync(srcPath, 'utf8');
    const $ = cheerio.load(html);

    // Remove existing stylesheets and inline styles
    $('link[rel="stylesheet"]').remove();
    $('style').remove();
    $('template').remove(); // Remove Next.js RSC streaming placeholders

    // Remove executable scripts to prevent SPA hydration crashes on static HTML exports
    $('script').each((_, el) => {
      const type = $(el).attr('type');
      const isExecutable = !type || /^(text|application)\/(javascript|ecmascript)$/i.test(type) || type === 'module';
      if (isExecutable) {
        $(el).remove();
      }
    });

    // Determine relative path to css/styles.css
    const pageDir = path.dirname('/' + page.local_path.replace(/\\/g, '/'));
    let relativeCssPath = path.posix.relative(pageDir, '/css/styles.css');
    if (relativeCssPath === '') relativeCssPath = 'styles.css';

    const routeNavigatorHTML = generateRouteNavigatorScript(routes, 'html');
    const fetchRewriteScript = generateFetchRewriteScript(pathMapping);

    // Inject our merged stylesheet, interactivity script, and navigator
    $('head').prepend(UNIVERSAL_STUBS_SCRIPT);
    if (fetchRewriteScript) $('head').append(fetchRewriteScript);
    $('head').append(`\n  <link rel="stylesheet" href="${relativeCssPath}">\n`);
    $('body').append(STATIC_INTERACTIVITY_SCRIPT);
    $('body').append(routeNavigatorHTML);

    html = $.html();
    html = rewriteHtmlPaths(html, pathMapping, page.local_path.replace(/\\/g, '/'), cloneRecord.url);
    html = rewriteInternalLinks(html, page.local_path);
    
    // Format with prettier
    const formattedHtml = await formatWithPrettier(html, 'html');

    // Save
    const destPath = path.join(outputDir, page.local_path);
    fs.mkdirSync(path.dirname(destPath), { recursive: true });
    fs.writeFileSync(destPath, formattedHtml);
  }

  // 4. Generate README
  const readme = `# ${cloneRecord.domain} - Clean HTML Export

This project was generated by Clony from ${cloneRecord.url} on ${new Date().toLocaleString()}.

## Structure
- \`index.html\`: The main landing page
- \`css/styles.css\`: Consolidated styles
- \`images/\`, \`fonts/\`, \`js/\`: Organized assets

## Viewing the Site
Do not open \`index.html\` directly in your browser by double-clicking it (\`file:///\` protocol). 
Modern browsers strictly enforce CORS policies that will block local fonts, videos, and some images from loading.

To view the site properly, start a local web server in this folder:
- **VS Code**: Use the "Live Server" extension
- **Node.js**: Run \`npx serve .\`
- **Python**: Run \`python -m http.server 3000\`
`;
  fs.writeFileSync(path.join(outputDir, 'README.md'), readme);
}
