import fs from 'fs';
import path from 'path';
import * as cheerio from 'cheerio';
import { formatWithPrettier, rewriteInternalLinks, STATIC_INTERACTIVITY_SCRIPT, UNIVERSAL_STUBS_SCRIPT, rewriteHtmlPaths } from './exportUtils.js';

const MAX_INLINE_SIZE = 2 * 1024 * 1024; // 2MB

export async function generate(sourceDir, outputDir, cloneRecord, pages, assets) {
  // Map hash -> asset object for quick lookup
  const assetMap = new Map();
  for (const asset of assets) {
    const hashName = path.basename(asset.local_path);
    assetMap.set(hashName, asset);
  }

  function getBase64DataUri(hashName) {
    const asset = assetMap.get(hashName);
    if (!asset || asset.size_bytes > MAX_INLINE_SIZE) return null;
    
    const srcPath = path.join(sourceDir, asset.local_path);
    if (!fs.existsSync(srcPath)) return null;

    const data = fs.readFileSync(srcPath);
    const mime = asset.content_type || 'application/octet-stream';
    return `data:${mime};base64,${data.toString('base64')}`;
  }

  function resolveHash(urlStr) {
    // extract hash from url like "../../_assets/12345.png"
    try {
      if (urlStr.startsWith('data:') || urlStr.startsWith('http')) return null;
      const basename = path.posix.basename(urlStr);
      // Strip query/hash if any
      const hashName = basename.split(/[?#]/)[0];
      return hashName;
    } catch(e) {
      return null;
    }
  }

  function inlineCssUrls(cssContent) {
    return cssContent.replace(/url\(['"]?([^'"()]+)['"]?\)/g, (match, url) => {
      const hashName = resolveHash(url);
      if (hashName) {
        const dataUri = getBase64DataUri(hashName);
        if (dataUri) return `url('${dataUri}')`;
      }
      return match;
    });
  }

  // 1. Process each HTML page
  for (const page of pages) {
    const srcPath = path.join(sourceDir, page.local_path);
    if (!fs.existsSync(srcPath)) continue;

    let html = fs.readFileSync(srcPath, 'utf8');
    const $ = cheerio.load(html);
    
    $('template').remove(); // Remove Next.js RSC streaming placeholders

    // Inline stylesheets
    $('link[rel="stylesheet"]').each((_, el) => {
      const href = $(el).attr('href');
      const hashName = resolveHash(href);
      if (hashName) {
        const asset = assetMap.get(hashName);
        if (asset) {
          const assetPath = path.join(sourceDir, asset.local_path);
          if (fs.existsSync(assetPath)) {
            let css = fs.readFileSync(assetPath, 'utf8');
            css = inlineCssUrls(css);
            $(el).replaceWith(`\n<style>\n/* Inlined from ${href} */\n${css}\n</style>\n`);
            return;
          }
        }
      }
    });

    // Inline images & media
    $('img[src], source[src]').each((_, el) => {
      const src = $(el).attr('src');
      const hashName = resolveHash(src);
      if (hashName) {
        const dataUri = getBase64DataUri(hashName);
        if (dataUri) {
          $(el).attr('src', dataUri);
        } else {
          $(el).after('<!-- Clony: asset too large to inline or missing -->');
        }
      }
    });

    // Inline srcset
    $('[srcset]').each((_, el) => {
      const srcset = $(el).attr('srcset');
      if (srcset) {
        const parts = srcset.split(',').map(part => {
          const [url, size] = part.trim().split(/\s+/);
          const hashName = resolveHash(url);
          if (hashName) {
            const dataUri = getBase64DataUri(hashName);
            if (dataUri) {
              return `${dataUri}${size ? ' ' + size : ''}`;
            }
          }
          return part;
        });
        $(el).attr('srcset', parts.join(', '));
      }
    });

    // Inline style attributes
    $('[style]').each((_, el) => {
      let style = $(el).attr('style');
      if (style && style.includes('url(')) {
        style = inlineCssUrls(style);
        $(el).attr('style', style);
      }
    });

    // Inline <style> blocks
    $('style').each((_, el) => {
      let css = $(el).html();
      if (css && css.includes('url(')) {
        css = inlineCssUrls(css);
        $(el).html(css);
      }
    });

    // Remove executable scripts to prevent SPA hydration crashes on file:/// URLs
    // (SPAs like Next.js crash when they see file:/// and wipe the DOM blank)
    $('script').each((_, el) => {
      const type = $(el).attr('type');
      const isExecutable = !type || /^(text|application)\/(javascript|ecmascript)$/i.test(type) || type === 'module';
      if (isExecutable) {
        $(el).remove();
      }
    });

    // Prepend Clony banner and append interactivity script
    $('head').prepend(UNIVERSAL_STUBS_SCRIPT);
    $('body').prepend(`\n<!-- Cloned from: ${cloneRecord.url} | Generated by Clony | Date: ${new Date().toLocaleString()} -->\n`);
    $('body').append(STATIC_INTERACTIVITY_SCRIPT);

    html = $.html();
    html = rewriteHtmlPaths(html, new Map(), page.local_path.replace(/\\/g, '/'), cloneRecord.url);
    html = rewriteInternalLinks(html, page.local_path);
    const formattedHtml = await formatWithPrettier(html, 'html');

    // Save
    const destPath = path.join(outputDir, page.local_path);
    fs.mkdirSync(path.dirname(destPath), { recursive: true });
    fs.writeFileSync(destPath, formattedHtml);
  }

  // 2. Generate README
  const readme = `# ${cloneRecord.domain} - Single HTML Export

This project was generated by Clony from ${cloneRecord.url} on ${new Date().toLocaleString()}.

## Structure
Each page from the cloned site has been exported as a self-contained HTML file. 
All CSS, images, fonts, and scripts have been inlined directly into the files using base64 data URIs.

Files larger than 2MB are skipped to prevent the HTML from crashing the browser.

To view the site, simply open \`index.html\` in any web browser. Navigation links between the pages will work locally.
`;
  fs.writeFileSync(path.join(outputDir, 'README.md'), readme);
}
